# Generated by Django 4.2.7 on 2023-11-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(choices=[('R', 'Released'), ('I', 'In Stock'), ('O', 'Out of Stock')], default='I', max_length=1)),
                ('headband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.headband')),
            ],
        ),
    ]
