# Generated by Django 4.2.7 on 2023-11-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accessory_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='headband',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
